# Generated by Django 3.0.7 on 2020-06-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Searcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_consumer_key', models.CharField(max_length=200)),
                ('t_consumer_secret', models.CharField(max_length=200)),
                ('t_access_token', models.CharField(max_length=200)),
                ('r_client_id', models.CharField(max_length=200)),
                ('r_client_secret', models.CharField(max_length=200)),
                ('r_username', models.CharField(max_length=200)),
                ('r_password', models.CharField(max_length=200)),
            ],
        ),
    ]
