# Generated by Django 3.0.7 on 2020-06-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robin_scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Searcher',
        ),
    ]
